package dev.codestijl.gradledocker;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * This class was generated by Gradle as part of the init process.
 */
@RestController
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class })
public class App {
    
    @RequestMapping("/")
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
        //System.out.println(new App().getGreeting());
    }
}
