package dev.codestijl.gradledocker;

import org.junit.Test;
import static org.junit.Assert.*;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;

import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.junit4.SpringRunner;
import dev.codestijl.gradledocker.config.SpringBootTestConfig;

/**
 * This class was generated by Gradle as part of the init process.
 */
@RunWith(SpringRunner.class)
@ContextConfiguration(classes={SpringBootTestConfig.class})
@TestPropertySource(value = "classpath:application.properties")
public class AppTest {

    @Autowired
	private SQLServerDataSource ds;

    @Test 
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
